### ISSUE TITLE
java

### ISSUE THREAD

**Issue by caneleex** [niklas2810/my-discord-butler#4]
why bot no kotlin kotlin superior

**Comment by BomBardyGamer** [comment]
das some fax right there my man

**Comment by niklas2810** [comment]
Nah

**Comment by markozajc** [comment]
java is too op

**Comment by Sanduhr32** [comment]
kotlin brokep

**Comment by markozajc** [comment]
this man knows

**Comment by BomBardyGamer** [comment]
lol

**Comment by Sanduhr32** [comment]
> Repository owner locked and limited conversation to collaborators on 26 Jul
> Repository owner unlocked this conversation on 26 Jul

What the hell happened here?

**Comment by niklas2810** [comment]
Basic existential crisis, nothing to worry about @Sanduhr32

**Comment by Sanduhr32** [comment]
We can raid your repo again with your permission

**Comment by niklas2810** [comment]
Nah, that would only remind me of the shame that I abandoned this side project 😂
